### ISSUE TITLE
NetworkOnMainThreadException during disconnect()

### ISSUE THREAD

**Issue by jhansche** [ParsePlatform/ParseLiveQuery-Android#21]
The act of disconnecting the client attempts to perform a network request on the main thread, leading to a crash:

```
Caused by android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
       at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1115)
       at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1110)
       at com.firebase.tubesock.WebSocket.closeSocket(WebSocket.java:223)
       at com.firebase.tubesock.WebSocket.close(WebSocket.java:197)
       at com.parse.TubeSockWebSocketClient.close(TubeSockWebSocketClient.java:65)
       at com.parse.ParseLiveQueryClientImpl.disconnect(ParseLiveQueryClientImpl.java:102)
```

All other network-related tasks are done in a background TaskExecutor.  But `disconnect()`, which calls `WebSocket.close()`, is not happening on that background thread.

**Comment by rogerhu** [comment]
One more reason I'd use the OkHttp version.  It handles its own threading. 

https://medium.com/square-corner-blog/web-sockets-now-shipping-in-okhttp-3-5-463a9eec82d1

**Comment by jhansche** [comment]
Fair enough. But if that's going to be a longer discussion or longer implementation time, I'm just going to work on fixing it in TubeSock for now.
